- name: left_column
  elements: [subheadline, text, code, guide, screenshot, newsletter]

- name: right_column
  elements: [subheadline, text, code, features_table, newsletter]

- name: slide_gallery
  elements: [slide]

- name: packages
  elements: [package]
