- name: headline
  contents:
  - name: headline
    type: EssenceText

- name: subheadline
  contents:
  - name: subheadline
    type: EssenceText

- name: text
  contents:
  - name: bigtext
    type: EssenceRichtext

- name: footer_column
  contents:
  - name: addthis_profile
    type: EssenceText
  - name: bigtext
    type: EssenceRichtext

- name: slide
  contents:
  - name: image
    type: EssencePicture
  - name: headline
    type: EssenceText
  - name: subheadline
    type: EssenceText

- name: code
  contents:
  - name: block
    type: EssenceHtml

- name: features_table
  unique: true
  contents:
  - name: headline
    type: EssenceText
  - name: features
    type: EssenceRichtext

- name: gallery
  picture_gallery: true

- name: screenshot
  picture_gallery: true

- name: guide
  unique: true
  contents:
  - name: text
    type: EssenceRichtext
