- name: headline
  contents:
  - name: headline
    type: EssenceText

- name: subheadline
  contents:
  - name: subheadline
    type: EssenceText

- name: text
  contents:
  - name: bigtext
    type: EssenceRichtext

- name: footer_column
  contents:
  - name: addthis_profile
    type: EssenceText
  - name: headline
    type: EssenceText
  - name: bigtext
    type: EssenceRichtext

- name: slide
  contents:
  - name: image
    type: EssencePicture
  - name: headline
    type: EssenceText
  - name: subheadline
    type: EssenceText

- name: package
  contents:
  - name: name
    type: EssenceText
  - name: description
    type: EssenceRichtext
  - name: default_days
    type: EssenceText
    default: 3
    hint: "Vorausgefüllte Anzahl von Tagen"
  - name: min_days
    type: EssenceText
    default: 1
    hint: "Minimum Anzahl von Tagen, die ausgewählt werden können."
  - name: amount_per_day
    type: EssenceText
    default: 1040
    hint: "Betrag pro Tag. Bitte ohne Währung angeben."
  - name: payment
    type: EssenceSelect
  - name: success_page
    type: EssenceSelect
    hint: "Seite, die aufgerufen wird, nachdem die PayPal Bezahlung erfolgt ist."
  - name: abort_page
    type: EssenceSelect
    hint: "Seite, die aufgerufen wird, wenn die PayPal Bezahlung abgebrochen wurde."

- name: code
  contents:
  - name: block
    type: EssenceHtml

- name: features_table
  unique: true
  contents:
  - name: headline
    type: EssenceText
  - name: features
    type: EssenceRichtext

- name: gallery
  picture_gallery: true

- name: screenshot
  picture_gallery: true

- name: newsletter
  unique: true
  contents:
  - name: headline
    type: EssenceText
  - name: text
    type: EssenceRichtext
  - name: email_label
    type: EssenceText
    default: Email Address
  - name: button_label
    type: EssenceText
    default: Subscribe
