- name: intro
  unique: true

- name: standard
  elements:
  - headline
  - subheadline
  - text
  - gallery
  - slide
  - code
  - screenshot
  - package
  - newsletter
  - slide_gallery
  - packages
  autogenerate:
  - slide_gallery
  - packages

- name: two_columns
  elements:
  - headline
  - subheadline
  - text
  - slide
  - code
  - features_table
  - screenshot
  - newsletter
  - left_column
  - right_column
  - slide_gallery
  autogenerate:
  - left_column
  - right_column
  - slide_gallery

- name: footer
  elements:
  - footer_column
  layoutpage: true

- name: community
  cache: false
  elements:
  - headline
  - subheadline
  - text
  - slide
  - code
  - features_table
  - screenshot
  - newsletter
  - left_column
  - right_column
  - slide_gallery
  autogenerate:
  - left_column
  - right_column
  - slide_gallery

- name: external
  redirects_to_external: true

- name: search_results
  cache: false
  searchresults: true

- name: showcases
  unique: true
  layoutpage: true
  elements:
  - headline
  - text

- name: extensions
  unique: true
  layoutpage: true
  elements:
  - headline
  - text
