---

- name: Add brightbox Ruby repository
  apt_repository:
    repo: ppa:brightbox/ruby-ng

- name: Install Ruby
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - ruby2.5
    - ruby2.5-dev

- name: Install Bundler
  gem:
    name: bundler
    state: latest
    user_install: no
