# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec0a17659ee4832ec8d232fc5af633fde5f65689827e29d6ea7e6d9220fad56700dbf989e3d6def1451055485760bffdd55b381d403d878416b6c826609dcce8

test:
  secret_key_base: 4078b3d67c9717cd3b40c3324866488bac08ad8bd601f7f18ee833eabc611c026e8eef4c2fc7caed932023851d0821706a1a44cffaf3f21c2d3f11ba52811f43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
