name: Deploy with Capistrano

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.5
    - uses: tvdeyen/capistrano-deploy@no-install-deps
      with:
        target: production
        deploy_key: ${{ secrets.DEPLOY_ENC_KEY }}
